# Regression

## Individual assignments

### Import of libraries and file

In [31]:
import matplotlib as plt
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [37]:
df = pd.read_csv("Flaveria.csv")
target = df['Plant Weight(g)']

### Assigning dummievalues

In [38]:
df_dummies = pd.get_dummies(df, columns =['N level','species'] )
df = df_dummies
updated_feature_names = ['N level_H','N level_L','N level_M','species_bidentis','species_brownii','species_pringlei',
                        'species_ramosissima','species_robusta','species_trinervia']

In [5]:
df_x=pd.DataFrame(df,columns = updated_feature_names)

In [39]:
df_y=pd.DataFrame(df,columns=target)

### Fit and predict

In [45]:
lm = linear_model.LinearRegression();

In [43]:
# with training
x_train,x_test,y_train,y_test = train_test_split(df_x,df_y,test_size=0.2)
lm.fit(x_train,y_train)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [46]:
# without training
X = df
y = target
model = lm.fit(X,y)

In [47]:
# /wo training
lm.predict(X)

array([ 0.3008,  0.3288,  0.3304,  0.388 ,  0.406 ,  0.3955,  0.3797,
        0.2962,  0.3881,  0.5194,  0.4667,  0.3504,  0.4592,  0.369 ,
        0.4804,  0.2786,  0.372 ,  0.3684,  0.3254,  0.4627,  0.4135,
        0.3943,  0.3981,  0.384 ,  0.4063,  0.3572,  0.32  ,  0.3329,
        0.3371,  0.4331,  0.4266,  0.3661,  0.4   ,  0.425 ,  0.5031,
        0.6128,  0.3372,  0.4137,  0.4464,  0.5098,  0.356 ,  0.5362,
        0.652 ,  0.4972,  0.5654,  0.4328,  0.4617,  0.3044])

In [26]:
# /w training
lm.predict(x_test)

array([[ 0.44238281],
       [ 0.34570312],
       [ 0.43164062],
       [ 0.38867188],
       [ 0.39355469],
       [ 0.37304688],
       [ 0.34570312],
       [ 0.43652344],
       [ 0.484375  ],
       [ 0.49511719]])

In [48]:
lm.coef_

array([ 1.        ,  0.00665521,  0.00665521,  0.00665521,  0.00331629,
        0.00331629,  0.00331629,  0.00331629,  0.00331629,  0.00331629])

### R² score

In [51]:
lm.score(X,y)

1.0