# Regression

## Individual assignments

### Import of libraries and file

In [1]:
import matplotlib as plt
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("Flaveria.csv")
target = df['Plant Weight(g)']

### Assigning dummievalues

In [3]:
df_dummies = pd.get_dummies(df, columns =['N level','species'] )
df = df_dummies
updated_feature_names = ['N level_H','N level_L','N level_M','species_bidentis','species_brownii','species_pringlei',
                        'species_ramosissima','species_robusta','species_trinervia']

In [4]:
df_x=pd.DataFrame(df,columns = updated_feature_names)

In [5]:
df_y=target

### R² score - decision tree

In [6]:
from sklearn.tree import DecisionTreeRegressor

In [81]:
X = df_x
y = df_y

In [79]:
import matplotlib.pyplot as plt

regressor = DecisionTreeRegressor(max_depth=7)
regressor.fit(X,y)

DecisionTreeRegressor(criterion='mse', max_depth=7, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [76]:
regressor.predict(X)

array([ 0.3148    ,  0.3148    ,  0.3748    ,  0.3748    ,  0.3748    ,
        0.35713333,  0.35713333,  0.35713333,  0.45806667,  0.45806667,
        0.45806667,  0.4048    ,  0.4048    ,  0.376     ,  0.376     ,
        0.376     ,  0.35526667,  0.35526667,  0.35526667,  0.4235    ,
        0.4235    ,  0.4235    ,  0.39105   ,  0.39105   ,  0.38175   ,
        0.38175   ,  0.33      ,  0.33      ,  0.33      ,  0.4086    ,
        0.4086    ,  0.4086    ,  0.4427    ,  0.4427    ,  0.4427    ,
        0.475     ,  0.475     ,  0.45663333,  0.45663333,  0.45663333,
        0.51473333,  0.51473333,  0.51473333,  0.49846667,  0.49846667,
        0.49846667,  0.38305   ,  0.38305   ])

In [77]:
regressor.score(X,y)

0.47014426975945056

### R² score - Ridge

In [11]:
lm = linear_model.Ridge(normalize=True);

In [12]:
model = lm.fit(X,y)

In [13]:
lm.predict(X)

array([ 0.38274346,  0.38274346,  0.38324314,  0.38324314,  0.38324314,
        0.37197172,  0.37197172,  0.37197172,  0.41594116,  0.41594116,
        0.41594116,  0.41644085,  0.41644085,  0.40516943,  0.40516943,
        0.40516943,  0.40198629,  0.40198629,  0.40198629,  0.40248598,
        0.40248598,  0.40248598,  0.39121456,  0.39121456,  0.39323664,
        0.39323664,  0.39373632,  0.39373632,  0.39373632,  0.38246491,
        0.38246491,  0.38246491,  0.43886389,  0.43886389,  0.43886389,
        0.43936357,  0.43936357,  0.42809216,  0.42809216,  0.42809216,
        0.44884766,  0.44884766,  0.44884766,  0.44934734,  0.44934734,
        0.44934734,  0.43807593,  0.43807593])

In [14]:
lm.coef_

array([-0.00734772,  0.00342401,  0.0039237 ,  0.03524447, -0.03085973,
        0.00233798, -0.02036654,  0.02526071, -0.01161689])

In [15]:
lm.intercept_

0.41017916666666671

In [16]:
lm.score(X,y)

0.24113551808562297

### Testing area

In [17]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)  

In [18]:
from sklearn.tree import DecisionTreeRegressor  
regressor = DecisionTreeRegressor()  
TEST = regressor.fit(X_train, y_train) 

In [19]:
y_pred = regressor.predict(X_test)  
regressor.score(X_test,y_test)

-0.40577653865062469

In [20]:
df=pd.DataFrame({'Actual':y_test["Plant Weight(g)"], 'Predicted':y_pred})  
df

KeyError: 'Plant Weight(g)'

In [ ]:
from sklearn import metrics  
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred))) 