# Regression

## Individual assignments

### Import of libraries and file

In [31]:
import matplotlib as plt
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [37]:
df = pd.read_csv("Flaveria.csv")
target = df['Plant Weight(g)']

### Assigning dummievalues

In [38]:
df_dummies = pd.get_dummies(df, columns =['N level','species'] )
df = df_dummies
updated_feature_names = ['N level_H','N level_L','N level_M','species_bidentis','species_brownii','species_pringlei',
                        'species_ramosissima','species_robusta','species_trinervia']

In [5]:
df_x=pd.DataFrame(df,columns = updated_feature_names)

In [69]:
df_y=pd.DataFrame(target)

### R² score - decision tree

In [113]:
from sklearn.tree import DecisionTreeRegressor

In [114]:
X = df_x
y = df_y

In [115]:
import matplotlib.pyplot as plt

regressor = DecisionTreeRegressor(max_depth=2)
regressor.fit(X,y)

DecisionTreeRegressor(criterion='mse', max_depth=2, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [116]:
regressor.predict(X)

array([ 0.38234062,  0.38234062,  0.38234062,  0.38234062,  0.38234062,
        0.38234062,  0.38234062,  0.38234062,  0.38234062,  0.38234062,
        0.38234062,  0.38234062,  0.38234062,  0.38234062,  0.38234062,
        0.38234062,  0.38234062,  0.38234062,  0.38234062,  0.38234062,
        0.38234062,  0.38234062,  0.38234062,  0.38234062,  0.38234062,
        0.38234062,  0.38234062,  0.38234062,  0.38234062,  0.38234062,
        0.38234062,  0.38234062,  0.456     ,  0.456     ,  0.456     ,
        0.456     ,  0.456     ,  0.456     ,  0.456     ,  0.456     ,
        0.5066    ,  0.5066    ,  0.5066    ,  0.5066    ,  0.5066    ,
        0.5066    ,  0.38305   ,  0.38305   ])

In [117]:
regressor.score(X,y)

0.31453275403981495

### R² score - Ridge

In [126]:
lm = linear_model.Ridge(normalize=True);

In [127]:
model = lm.fit(X,y)

In [133]:
lm.predict(X)

array([[ 0.38274346],
       [ 0.38274346],
       [ 0.38324314],
       [ 0.38324314],
       [ 0.38324314],
       [ 0.37197172],
       [ 0.37197172],
       [ 0.37197172],
       [ 0.41594116],
       [ 0.41594116],
       [ 0.41594116],
       [ 0.41644085],
       [ 0.41644085],
       [ 0.40516943],
       [ 0.40516943],
       [ 0.40516943],
       [ 0.40198629],
       [ 0.40198629],
       [ 0.40198629],
       [ 0.40248598],
       [ 0.40248598],
       [ 0.40248598],
       [ 0.39121456],
       [ 0.39121456],
       [ 0.39323664],
       [ 0.39323664],
       [ 0.39373632],
       [ 0.39373632],
       [ 0.39373632],
       [ 0.38246491],
       [ 0.38246491],
       [ 0.38246491],
       [ 0.43886389],
       [ 0.43886389],
       [ 0.43886389],
       [ 0.43936357],
       [ 0.43936357],
       [ 0.42809216],
       [ 0.42809216],
       [ 0.42809216],
       [ 0.44884766],
       [ 0.44884766],
       [ 0.44884766],
       [ 0.44934734],
       [ 0.44934734],
       [ 0

In [134]:
lm.coef_

array([[-0.00734772,  0.00342401,  0.0039237 ,  0.03524447, -0.03085973,
         0.00233798, -0.02036654,  0.02526071, -0.01161689]])

In [135]:
lm.intercept_

array([ 0.41017917])

In [136]:
lm.score(X,y)

0.24113551808562297

### Testing area

In [137]:
from sklearn.cross_validation import cross_val_score
from sklearn.cross_validation import KFold
crossvalidation = KFold(n=X.shape[0], n_folds=5,
 shuffle=True, random_state=1)

C:\Users\milli\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [144]:
from sklearn.tree import DecisionTreeRegressor
regression_tree = tree.DecisionTreeRegressor(
 min_samples_split=30, min_samples_leaf=10,random_state=0)
regression_tree.fit(X,y)
score = np.mean(cross_val_score(regression_tree, X, y, scoring="mean_squared_error", cv=crossvalidation,n_jobs=1))
print ‘Mean squared error: %.3f’ % abs(score)

SyntaxError: invalid character in identifier (<ipython-input-144-a96cba7c3160>, line 8)